spring:
  application:
    name: my-app

  profiles:
    active: dev  # switch to 'prod' when deploying

  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # options: validate | update | create | create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    user:
      name: admin
      password: secret

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

logging:
  level:
    root: info
    com.myapp: debug
  file:
    name: logs/my-app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: "*"
---

# Development profile using H2
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: user
    password: pass
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081
---

# Production profile with PostgreSQL
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://prod-db-host:5432/prod_database
    username: prod_user
    password: prod_password
    driver-class-name: org.postgresql.Driver

server:
  port: 80

