spring:
  application:
    name: my-app
  profiles:
    active: dev # Change to 'prod' for production mode

  # Server Port
  server:
    port: 8080

  # Multipart file settings
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
